name=CircularBuffer
version=1.0.0
author=oskza
maintainer=dev@oskza.com
sentence=Generic, template-based, fixed-size circular buffer in C++ for Arduino & desktop.
paragraph=Generic, template-based, fixed-size circular buffer in C++ for Arduino & desktop.
category=Data Storage
url=https://github.com/oskza/CircularBuffer
architectures=*
license=MIT
